name: Checks for clicker-backend

on:
  push:
    paths:
      - 'clicker-backend/**'
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clicker-backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Check build
        run: npm run build

      - name: Check lint rules
        run: npm run lint

      - name: Check codestyle
        run: npm run codestyle

      - name: Check types
        run: npm run ts

      - name: Run tests
        run: npm run test:ci

      - name: Run tests E2E
        run: npm run test:e2e
